### PR TITLE
Feature/improving multi asa size

### PR DESCRIPTION
**Pull request by aorumbayev**
### Description

> _Please explain the changes you made here_

- Fixes a size limit on multi asa swap
- Fits up to 5 asas (max was 4 before that, overflow by ~80 bytes)
- Adding unit test that generates up to 5 random asas of random amount and units 
- Refinements in CI

### Checklist

> _Please, make sure to comply with the checklist below before expecting review_

- [x] Code compiles correctly
- [x] Created tests which fail without the change (if possible)
- [x] All tests passing
- [x] Extended the README / documentation, if necessary

### CODE REVIEW

**Review by cusma — COMMENTED** [review]
This looks generally good to me. Given the `multi_asa_optin` is _"permissioned"_ I'm fine with relaxing some checks on the `multi_asa_optin_preconditions` (see my comment to `asas_to_algo_swapper.py`).

This being said, since this PR aims to solve the [1kb limit size on compiled TEAL code](https://developer.algorand.org/docs/get-details/parameter_tables/#smart-signature-constraints) for SmartSig, as second step, I would try to pursue also another tentative in making the compiled TEAL more _"size efficient"_.

I would try to restore all the original checks on `multi_asa_optin` while making the code more _"size efficient"_ with a refactoring that makes use of `@Subroutine` that handle common repeated checks (like `_max_fee`, `_rekey_to`, `_asset_close_to`). Using `@Subroutine` the swapper could maybe end up being able to handle multi ASA swaps grater than 5 ASA.

**Comment by aorumbayev** [comment]
@cusma thanks for the review. Just to recap the key points, if i got it correctly - the gist is to restore the precondition and DRY out some methods to remove repeating statements and thats it?

**Comment by cusma** [comment]
> Let me know what you think (also made an issue for myself to track this -> #19).

I totally agree: this second major refactoring should be handled in a different PR. I'm ok in merging this for the hotfix.

Further steps for a separate PR could be:

1. Restore original checks.
2. Option A: Introduce `@Subroutine` to make repeated checks more modular and reducing code repetition.
3. Evaluate improvements as number of concurrent ASA in the Multi ASA swap.
4. Option B: Relaxing checks on `multi_asa_optin` in the new `@Subroutine` refactoring.
5. Evaluate further improvements as number of concurrent ASA in the Multi ASA swap.
6. Trade offs between options A (`@Subroutine` refactoring) and B (`@Subroutine` refactoring + `multi_asa_optin` checks relaxing).
7. Implement A or B.

**Comment by aorumbayev** [comment]
Awesome, ill resolve the existing comments for now but i have the reference to pr via the issue so ill get back to your remarks once ill start working on the follow up pr ;)

**Pull request merged**
